[tool.poetry]
name = "django_ocr_backend"
version = "0.1.0"
description = "This is to be the backend of my Python OCR project."
authors = ["Joseph Cardenas <josephvcardenas@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
