[tool.poetry]
name = "django-ocr-backend"
version = "0.1.0"
description = ""
authors = ["Joseph Cardenas <josephvcardenas@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django-storages = "^1.9.1"
gunicorn = "^20.0.4"
djangorestframework = "^3.11.1"
django-heroku = "^0.3.1"
django-cors-headers = "^3.4.0"
whitenoise = "^5.2.0"
pytesseract = "^0.3.5"
OCRmyPDF = "^11.0.1"
ghostscript = "^0.6"
boto3 = "^1.14.47"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
