# Generated by Django 3.0.6 on 2020-05-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20200503_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
