# Generated by Django 3.1.3 on 2020-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(default='file', upload_to='post_files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
