# Generated by Django 3.0.4 on 2020-04-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OCR_file',
            new_name='OCRFile',
        ),
    ]
