# Generated by Django 3.1.3 on 2020-12-11 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=True, max_length=250, unique_for_date='uploaded'),
        ),
        migrations.AddField(
            model_name='post',
            name='uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
