# Generated by Django 3.1.1 on 2020-09-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_auto_20200520_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(default='file', upload_to='post_files'),
        ),
    ]
